# Generated by Django 2.0.3 on 2020-10-20 06:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('about_us', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='slider/')),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'about_us',
                'verbose_name_plural': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='beauty_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='tips/')),
                ('tips', ckeditor.fields.RichTextField()),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'beauty_care',
                'verbose_name_plural': 'beauty_care',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('add_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='tips/')),
                ('tips', ckeditor.fields.RichTextField()),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'corona',
                'verbose_name_plural': 'corona',
            },
        ),
        migrations.CreateModel(
            name='health_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='tips/')),
                ('tips', ckeditor.fields.RichTextField()),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'health_care',
                'verbose_name_plural': 'health_care',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='logo/')),
                ('icon', models.ImageField(blank=True, upload_to='logo/')),
                ('Status', models.BooleanField(default=True)),
                ('header_image', models.ImageField(blank=True, upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image1', models.ImageField(blank=True, upload_to='product/')),
                ('image2', models.ImageField(blank=True, upload_to='product/')),
                ('image3', models.ImageField(blank=True, upload_to='product/')),
                ('power', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('indication', models.TextField(blank=True)),
                ('dosage', models.TextField(blank=True)),
                ('side_efect', models.TextField(blank=True)),
                ('therapeutic_class', models.TextField(blank=True)),
                ('pack_price', models.CharField(blank=True, max_length=50)),
                ('new_price', models.CharField(max_length=50)),
                ('additional', models.TextField(blank=True)),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=150)),
                ('discription', models.TextField(blank=True, max_length=550)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slider/')),
                ('Title', models.CharField(max_length=150)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'slider',
            },
        ),
        migrations.CreateModel(
            name='store_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('store_map', models.TextField(blank=True)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'store_location',
                'verbose_name_plural': 'store_locations',
            },
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='disease/')),
                ('info', models.TextField(blank=True)),
                ('medicine1', models.CharField(blank=True, max_length=100)),
                ('medicine2', models.CharField(blank=True, max_length=100)),
                ('medicine3', models.CharField(blank=True, max_length=100)),
                ('medicine4', models.CharField(blank=True, max_length=100)),
                ('medicine5', models.CharField(blank=True, max_length=100)),
                ('food', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tips',
                'verbose_name_plural': 'tips',
            },
        ),
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user_message',
                'verbose_name_plural': 'user_messages',
            },
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user_reg',
                'verbose_name_plural': 'user_reg',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_reg',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.user_reg'),
        ),
    ]
