# Generated by Django 2.0.3 on 2020-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='our_history',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='our_mission',
        ),
        migrations.AddField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, upload_to='slider/'),
        ),
    ]
