# Generated by Django 2.0.3 on 2020-10-17 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_beauty_care_health_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='tips/')),
                ('tips', ckeditor.fields.RichTextField()),
                ('view', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'health_care',
                'verbose_name_plural': 'health_care',
            },
        ),
    ]
