# Generated by Django 2.0.3 on 2020-10-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_corona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corona',
            options={'verbose_name': 'corona', 'verbose_name_plural': 'corona'},
        ),
    ]
